return {
  {
    'nvim-treesitter/nvim-treesitter',
    lazy = false,
    build = ':TSUpdate',
    opts = {
      ensure_installed = {
        'bash',
        'diff',
        'dockerfile',
        'git_config',
        'git_rebase',
        'gitcommit',
        'gitignore',
        'go',
        'hyprlang',
        'jq',
        'json',
        'jsonnet',
        'lua',
        'make',
        'markdown',
        'nix',
        'python',
        'regex',
        'ssh_config',
        'toml',
        'vim',
        'vimdoc',
        'yaml',
      },
      auto_install = true,
    },
  },
  {
    'nvim-treesitter/nvim-treesitter-context',
    dependencies = { 'nvim-treesitter/nvim-treesitter' },
    event = { 'BufReadPost', 'BufNewFile' },
    opts = {
      max_lines = 3,
    },
  },
}
